services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: "pip install -r online/src/requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 upload:app"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    region: oregon
    rootDir: online/src
